# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('danger', models.CharField(max_length=255)),
                ('thing', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('money', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
    ]
